use new gnutls version 3.6.8

diff --git a/src/gnutls/tests/cert-tests/certtool b/src/gnutls/tests/cert-tests/certtool
--- a/src/gnutls/tests/cert-tests/certtool
+++ b/src/gnutls/tests/cert-tests/certtool
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-# Copyright (C) 2014 Nikos Mavrogiannopoulos
+# Copyright (C) 2014-2018 Nikos Mavrogiannopoulos
+# Copyright (C) 2018 Red Hat, Inc.
 #
 # This file is part of GnuTLS.
 #
@@ -14,15 +15,21 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 # General Public License for more details.
 #
-# You should have received a copy of the GNU General Public License
-# along with GnuTLS; if not, write to the Free Software Foundation,
-# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
+# You should have received a copy of the GNU Lesser General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>
 
 #set -e
 
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff -b -B}"
+TMPFILE1=certtool-file1.$$.tmp
+TMPFILE2=certtool-file2.$$.tmp
+PASS="1234"
+
+if test -n "$DISABLE_BASH_TESTS"; then
+	exit 77
+fi
 
 if ! test -x "${CERTTOOL}"; then
 	exit 77
@@ -30,6 +37,33 @@ fi
 
 if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+fi
+
+SETSID=$(which setsid)
+if test -n "${SETSID}";then
+	${VALGRIND} "${CERTTOOL}" --generate-privkey --rsa --outfile ${TMPFILE1} --pkcs8 --password ${PASS}
+	if test $? != 0;then
+		echo "private key generation failed"
+		exit 1
+	fi
+
+	#check whether password is being honoured
+	#some CI runners need GNUTLS_PIN (GNUTLS_PIN=${PASS})
+	${SETSID} "${CERTTOOL}" --generate-self-signed --load-privkey ${TMPFILE1} --template ${srcdir}/templates/template-test.tmpl --ask-pass >${TMPFILE2} 2>&1 <<EOF
+$PASS
+EOF
+	if test $? != 0;then
+		cat ${TMPFILE2}
+		echo "cert generation failed"
+		exit 1
+	fi
+
+	grep "Enter password" ${TMPFILE2} >/dev/null 2>&1
+	if test $? != 0;then
+		cat ${TMPFILE2}
+		echo "No password was asked"
+		exit 1
+	fi
 fi
 
 #check whether "funny" spaces can be interpreted
@@ -65,6 +99,14 @@ if test "${id}" != "118e72e3655150c895ecbd19b3634179fb4a87c7a25abefcb11f5d66661d
 	exit 1
 fi
 
+id=`"${CERTTOOL}" --pubkey-info <"${srcdir}/data/funny-spacing.pem"|"${CERTTOOL}" --key-id --hash sha512| tr -d '\r'`
+rc=$?
+
+if test "${id}" != "5e81ba533b1e7b88b3b0834a392c1cd63f8ccbe45f39edf4cb4b6a3e7700b333cfa386c54b1c5704a2b82a20dc417b347bb8f961c339134a91158a134ca6c478"; then
+	echo "Key-ID4 doesn't match the expected: ${id}"
+	exit 1
+fi
+
 #fingerprint
 id=`${VALGRIND} "${CERTTOOL}" --fingerprint --infile "${srcdir}/data/funny-spacing.pem"| tr -d '\r'`
 rc=$?
@@ -90,6 +132,22 @@ if test "${id}" != "c4880390506a849cd2d8289fb8aea8c189e635aff1054faba58658a0f107
 	exit 1
 fi
 
+# Test whether certtool --outder doesn't output the informational text data
+
+${VALGRIND} "${CERTTOOL}" -i --infile "${srcdir}/data/funny-spacing.pem" --outder --outfile ${TMPFILE1}
+if test $? != 0;then
+	echo "cert output to DER failed"
+	exit 1
+fi
+
+grep 'Version:' ${TMPFILE1}
+if test $? = 0;then
+	echo "found text info in DER certificate"
+	exit 1
+fi
+
+rm -f ${TMPFILE1} ${TMPFILE2}
+
 export TZ="UTC"
 
 . ${srcdir}/../scripts/common.sh
@@ -104,6 +162,5 @@ if test "${rc}" != "0"; then
 	echo "There was an issue verifying the chain"
 	exit 1
 fi
-
 
 exit 0
diff --git a/src/gnutls/tests/cert-tests/crl b/src/gnutls/tests/cert-tests/crl
--- a/src/gnutls/tests/cert-tests/crl
+++ b/src/gnutls/tests/cert-tests/crl
@@ -25,6 +25,7 @@ export TZ="UTC"
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
+ac_cv_sizeof_time_t="${ac_cv_sizeof_time_t:-8}"
 
 if ! test -x "${CERTTOOL}"; then
 	exit 77
@@ -37,7 +38,8 @@ fi
 OUTFILE=out-crl.$$.tmp
 INFOFILE=out-crl-info.$$.tmp
 OUTFILE2=out2-crl.$$.tmp
-TMPFILE=crl.$$.tmpl
+TMPFILE=crl.$$.tmp
+TMP2FILE=crl2.$$.tmp
 
 echo "crl_next_update = 43" >$TMPFILE
 echo "crl_number = 7" >>$TMPFILE
@@ -53,9 +55,29 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
+${VALGRIND} "${CERTTOOL}" --crl-info --infile ${OUTFILE} --no-text --outfile ${TMP2FILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text crl info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMP2FILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text crl info failed 2"
+	exit 1
+fi
+
 grep "Revoked certificates (152)" "${INFOFILE}" >/dev/null 2>&1
 if test "$?" != "0"; then
 	echo "CRL generation didn't succeed as expected"
+	exit 1
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "CRL Number (not critical): 07$" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL generation didn't succeed as expected (2)"
+	grep "CRL Number (not critical):" "${INFOFILE}"
 	exit 1
 fi
 
@@ -120,9 +142,167 @@ if test "$?" != "0"; then
 	exit 1
 fi
 
+# Check hex serial number
+echo "crl_next_update = 43" >$TMPFILE
+echo "crl_number = 0x1234567890abcdef1234567890abcdef12345678" >>$TMPFILE
+
+${VALGRIND} "${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key"  --load-ca-certificate \
+	"${srcdir}/data/template-test.pem" --load-certificate "${srcdir}/data/ca-certs.pem" --template \
+	"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+
+# We're done.
+if test "${rc}" != "0"; then
+	echo "CRL hex number failed"
+	exit ${rc}
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "CRL Number (not critical): 1234567890abcdef1234567890abcdef12345678$" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL hex number didn't succeed as expected"
+	grep "CRL Number (not critical):" "${INFOFILE}"
+	exit 1
+fi
+
+# Check default CRL number
+echo "crl_next_update = 43" >$TMPFILE
+
+export TZ="UTC"
+
+. ${srcdir}/../scripts/common.sh
+
+check_for_datefudge
+
+datefudge -s "2020-01-20 10:00:00" ${VALGRIND} \
+	"${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key" \
+	--load-ca-certificate "${srcdir}/data/template-test.pem" \
+	--load-certificate "${srcdir}/data/ca-certs.pem" --template \
+	"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+
+# We're done.
+if test "${rc}" != "0"; then
+	echo "CRL default number failed"
+	exit ${rc}
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "CRL Number (not critical): 5e257a20[0-9a-f]\{30\}$" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL default number didn't succeed as expected"
+	grep "CRL Number (not critical):" "${INFOFILE}"
+	exit 1
+fi
+
+if test "${ac_cv_sizeof_time_t}" = 8;then
+	# we should test that on systems which have 64-bit time_t
+	datefudge -s "2138-01-20 10:00:00" ${VALGRIND} \
+		"${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key" \
+		--load-ca-certificate "${srcdir}/data/template-test.pem" \
+		--load-certificate "${srcdir}/data/ca-certs.pem" --template \
+		"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+	rc=$?
+
+	# We're done.
+	if test "${rc}" != "0"; then
+		echo "CRL default number 2 failed"
+		exit ${rc}
+	fi
+
+	sed 's/\r$//' <"${INFOFILE}" | grep "CRL Number (not critical): 013c1972a0[0-9a-f]\{30\}$" >/dev/null 2>&1
+	if test "$?" != "0"; then
+		echo "CRL default number 2 didn't succeed as expected"
+		grep "CRL Number (not critical):" "${INFOFILE}"
+		exit 1
+	fi
+fi
+
+# Check large decimal CRL number
+echo "crl_next_update = 43" >$TMPFILE
+echo "crl_number = 1234567890123456789012345678" >>$TMPFILE
+
+${VALGRIND} "${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key"  --load-ca-certificate \
+	"${srcdir}/data/template-test.pem" --load-certificate "${srcdir}/data/ca-certs.pem" --template \
+	"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+
+# We're done.
+if test "${rc}" = "0"; then
+	echo "CRL large decimal number succeeded when shouldn't"
+	exit ${rc}
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "error parsing number: 1234567890123456789012345678" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL large number didn't fail as expected"
+	exit 1
+fi
+
+# Check invalid hex number
+echo "crl_next_update = 43" >$TMPFILE
+echo "crl_number = 0xsomething" >>$TMPFILE
+
+${VALGRIND} "${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key"  --load-ca-certificate \
+	"${srcdir}/data/template-test.pem" --load-certificate "${srcdir}/data/ca-certs.pem" --template \
+	"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+
+# We're done.
+if test "${rc}" = "0"; then
+	echo "CRL invalid hex number succeeded when shouldn't"
+	exit ${rc}
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "error parsing number: 0xsomething" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL invalid hex number didn't fail as expected"
+	exit 1
+fi
+
+# Check invalid number
+echo "crl_next_update = 43" >$TMPFILE
+echo "crl_number = something" >>$TMPFILE
+
+${VALGRIND} "${CERTTOOL}" --generate-crl --load-ca-privkey "${srcdir}/data/template-test.key"  --load-ca-certificate \
+	"${srcdir}/data/template-test.pem" --load-certificate "${srcdir}/data/ca-certs.pem" --template \
+	"${TMPFILE}" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+
+# We're done.
+if test "${rc}" = "0"; then
+	echo "CRL invalid number succeeded when shouldn't"
+	exit ${rc}
+fi
+
+sed 's/\r$//' <"${INFOFILE}" | grep "error parsing number: something" >/dev/null 2>&1
+if test "$?" != "0"; then
+	echo "CRL invalid number didn't fail as expected"
+	exit 1
+fi
+
+# Check CRL verification
+
+## CRL validation is expected to succeed
+${VALGRIND} "${CERTTOOL}" --verify-crl --infile "${srcdir}/data/ca-crl-valid.crl"  --load-ca-certificate \
+	"${srcdir}/data/ca-crl-valid.pem" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+if test "${rc}" != "0"; then
+	echo "CRL verification failed"
+	exit ${rc}
+fi
+
+## CRL validation is expected to fail because the CA doesn't have the CRLSign key usage flag
+${VALGRIND} "${CERTTOOL}" --verify-crl --infile "${srcdir}/data/ca-crl-invalid.crl"  --load-ca-certificate \
+	"${srcdir}/data/ca-crl-invalid.pem" >${OUTFILE} 2>${INFOFILE}
+rc=$?
+if test "${rc}" = "0"; then
+	echo "CRL verification succeeded when shouldn't"
+	exit 1
+fi
+
 rm -f "${OUTFILE}"
 rm -f "${INFOFILE}"
 rm -f "${OUTFILE2}"
 rm -f "${TMPFILE}"
+rm -f "${TMP2FILE}"
 
 exit 0
diff --git a/src/gnutls/tests/cert-tests/crq b/src/gnutls/tests/cert-tests/crq
--- a/src/gnutls/tests/cert-tests/crq
+++ b/src/gnutls/tests/cert-tests/crq
@@ -34,6 +34,7 @@ if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
 
+TMPFILE=crq.$$.tmp
 OUTFILE=out.$$.tmp
 OUTFILE2=out2.$$.tmp
 
@@ -65,6 +66,19 @@ datefudge -s "2007-04-22" \
 		--template "${srcdir}/templates/template-tlsfeature.tmpl" \
 		--outfile $OUTFILE 2>/dev/null
 
+${CERTTOOL} --crq-info --no-text --infile ${OUTFILE} --outfile ${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text crq info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMPFILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text crq info failed 2"
+	exit 1
+fi
+
 datefudge -s "2007-04-22" \
 	"${CERTTOOL}" --generate-certificate \
 		--load-ca-privkey "${srcdir}/data/template-test.key" \
@@ -84,5 +98,55 @@ if test "${rc}" != "0"; then
 fi
 
 rm -f "${OUTFILE}" "${OUTFILE2}"
+
+
+# Test interactive CRQ creation with very long input
+cat >$TMPFILE <<__EOF__
+super-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long.com
+
+
+
+
+
+
+
+super-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long.com
+
+
+
+
+
+
+
+
+N
+Y
+N
+Y
+N
+N
+N
+N
+N
+N
+__EOF__
+
+setsid \
+datefudge -s "2007-04-22" \
+	"${CERTTOOL}" -q \
+		--load-privkey "${srcdir}/data/template-test.key" \
+		--outfile "${OUTFILE}" <$TMPFILE 2>/dev/null
+
+${DIFF} --ignore-matching-lines "Algorithm Security Level" "${srcdir}/data/template-long-dns-crq.pem" "${OUTFILE}" >/dev/null 2>&1
+rc=$?
+
+# We're done.
+if test "${rc}" != "0"; then
+	echo "Certificate request generation with long DNS failed"
+	echo $OUTFILE
+	exit ${rc}
+fi
+
+rm -f "${OUTFILE}" "${OUTFILE2}" "${TMPFILE}"
 
 exit 0
diff --git a/src/gnutls/tests/cert-tests/pem-decoding b/src/gnutls/tests/cert-tests/pem-decoding
--- a/src/gnutls/tests/cert-tests/pem-decoding
+++ b/src/gnutls/tests/cert-tests/pem-decoding
@@ -24,7 +24,6 @@
 
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
-DIFF="${DIFF:-diff -b -B}"
 
 if ! test -x "${CERTTOOL}"; then
 	exit 77
@@ -33,6 +32,8 @@ fi
 if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
+
+. "${srcdir}/../scripts/common.sh"
 
 TMPFILE=tmp-$$.pem.tmp
 TMPFILE1=tmp1-$$.pem.tmp
@@ -57,8 +58,7 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-#FIXME: the output string differs in windows and linux on the last char.
-${DIFF} -I 'Algorithm Security Level' "${srcdir}/data/bmpstring.pem" ${TMPFILE} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${srcdir}/data/bmpstring.pem" ${TMPFILE}
+check_if_equal "${srcdir}/data/bmpstring.pem" ${TMPFILE} "Algorithm Security Level"
 rc=$?
 
 if test "${rc}" != "0"; then
@@ -75,9 +75,7 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-cat "${srcdir}/data/complex-cert.pem" |grep -v "Not After:" >${TMPFILE1}
-cat ${TMPFILE} |grep -v "Not After:" >${TMPFILE2}
-${DIFF} -I 'Algorithm Security Level' ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
+check_if_equal "${srcdir}/data/complex-cert.pem" ${TMPFILE} "Not After:|Algorithm Security Level"
 rc=$?
 
 if test "${rc}" != "0"; then
@@ -94,9 +92,7 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-cat "${srcdir}/data/xmpp-othername.pem" |grep -v "Not After:" >${TMPFILE1}
-cat ${TMPFILE} |grep -v "Not After:" >${TMPFILE2}
-${DIFF} -I 'Algorithm Security Level' ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
+check_if_equal "${srcdir}/data/xmpp-othername.pem" ${TMPFILE} "^warning|Not After:|Algorithm Security Level"
 rc=$?
 
 if test "${rc}" != "0"; then
@@ -112,9 +108,9 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-cat ${TMPFILE} |grep "KRB5Principal:" >${TMPFILE1}
-cat "${srcdir}/data/template-krb5name-full.pem" |grep "KRB5Principal:" >${TMPFILE2}
-${DIFF} -I 'Algorithm Security Level' -u ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' -u --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
+grep "KRB5Principal:" ${TMPFILE} >${TMPFILE1}
+grep "KRB5Principal:" "${srcdir}/data/template-krb5name-full.pem" >${TMPFILE2}
+check_if_equal ${TMPFILE1} ${TMPFILE2}
 rc=$?
 
 if test "${rc}" != "0"; then
@@ -124,7 +120,13 @@ fi
 
 
 #check whether the cert with GOST parameters is decoded as expected
-${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/gost-cert.pem" >${TMPFILE}
+if test "${ENABLE_GOST}" = "1"; then
+	GOSTCERT="${srcdir}/data/gost-cert.pem"
+else
+	GOSTCERT="${srcdir}/data/gost-cert-nogost.pem"
+fi
+
+${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${GOSTCERT}" >${TMPFILE}
 rc=$?
 
 if test "${rc}" != "0"; then
@@ -132,11 +134,28 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-${DIFF} -I 'Algorithm Security Level' ${TMPFILE} "${srcdir}/data/gost-cert.pem" || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${TMPFILE}" "${srcdir}/data/gost-cert.pem"
+check_if_equal ${TMPFILE} "${GOSTCERT}"
 rc=$?
 
 if test "${rc}" != "0"; then
 	echo "GOST cert decoding failed 2"
+	exit ${rc}
+fi
+
+#check whether the cert with GOST 31.10/11-94 parameters is decoded as expected
+${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/gost94-cert.pem" >${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "GOST94 cert decoding failed 1"
+	exit ${rc}
+fi
+
+check_if_equal ${TMPFILE} "${srcdir}/data/gost94-cert.pem" "Algorithm Security Level"
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "GOST94 cert decoding failed 2"
 	exit ${rc}
 fi
 
@@ -148,12 +167,55 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-${DIFF} -I 'Algorithm Security Level' ${TMPFILE} "${srcdir}/data/multi-value-dn.pem" || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${TMPFILE}" "${srcdir}/data/multi-value-dn.pem"
+# Needed for FIPS140 mode
+check_if_equal "${srcdir}/data/multi-value-dn.pem" ${TMPFILE} "Algorithm Security Level:"
 rc=$?
 
 if test "${rc}" != "0"; then
 	echo "MV-DN cert decoding failed 2"
 	exit ${rc}
+fi
+
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/cert-ecc256.pem" --no-text --outfile ${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text -k --certificate-info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMPFILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text -k --certificate-info failed 2"
+	exit 1
+fi
+
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --certificate-pubkey --infile "${srcdir}/data/cert-ecc256.pem" --no-text  --outfile ${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text cert pubkey failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMPFILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text cert pubkey failed 2"
+	exit 1
+fi
+
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --pubkey-info --infile "${srcdir}/data/cert-ecc256.pem" --no-text  --outfile ${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text pubkey info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMPFILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text pubkey info failed 2"
+	exit 1
 fi
 
 rm -f ${TMPFILE} ${TMPFILE1} ${TMPFILE2}
diff --git a/src/gnutls/tests/cert-tests/pkcs12 b/src/gnutls/tests/cert-tests/pkcs12
--- a/src/gnutls/tests/cert-tests/pkcs12
+++ b/src/gnutls/tests/cert-tests/pkcs12
@@ -28,6 +28,11 @@ if ! test -x "${CERTTOOL}"; then
 	exit 77
 fi
 
+if test "${GNUTLS_FORCE_FIPS_MODE}" = 1;then
+	echo "Cannot run in FIPS140-2 mode"
+	exit 77
+fi
+
 if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=1"
 fi
@@ -40,11 +45,11 @@ TMPFILE_PEM=pkcs12.$$.pem.tmp
 
 DEBUG="1"
 
-ret=0
-for p12 in "client.p12 foobar" "openssl.p12 CaudFocwijRupogDoicsApfiHadManUgNa" "noclient.p12" "unclient.p12" "pkcs12_2certs.p12"; do
+for p12 in "aes-128.p12 Red%20Hat%20Enterprise%20Linux%207.4" "pbes1-no-salt.p12 Red%20Hat%20Enterprise%20Linux%207.4" "no-salt.p12 Red%20Hat%20Enterprise%20Linux%207.4" "mac-sha512.p12 Red%20Hat%20Enterprise%20Linux%207.4" "cert-with-crl.p12 password" "client.p12 foobar" "openssl.p12 CaudFocwijRupogDoicsApfiHadManUgNa" "noclient.p12" "unclient.p12" "pkcs12_2certs.p12"; do
 	set -- ${p12}
 	file="$1"
-	passwd="$2"
+	passwd=$(echo $2|sed 's/%20/ /g')
+
 	if test "x$DEBUG" != "x"; then
 		${VALGRIND} "${CERTTOOL}" -d 99 --p12-info --inder --password "${passwd}" \
 			--infile "${srcdir}/data/${file}"
@@ -54,7 +59,7 @@ for p12 in "client.p12 foobar" "openssl.p12 CaudFocwijRupogDoicsApfiHadManUgNa" 
 	fi
 	rc=$?
 	if test ${rc} != 0; then
-		echo "NEON PKCS12 FATAL ${p12}"
+		echo "PKCS12 FATAL ${p12}"
 		exit 1
 	fi
 done
@@ -72,6 +77,19 @@ ${VALGRIND} "${CERTTOOL}" --p12-info --inder --password 1234 --infile "${file}" 
 rc=$?
 if test ${rc} != 0; then
 	echo "PKCS12 FATAL ${file}"
+	exit 1
+fi
+
+${VALGRIND} "${CERTTOOL}" --p12-info --inder --password 1234 --infile "$srcdir/data/sha256.p12" --outfile "${TMPFILE}" --no-text
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text pkcs12 info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$' ${TMPFILE} | grep -v '^[A-Za-z0-9/+=]\+$' | grep -v '^-----END [A-Z0-9 ]\+-----$' ; then
+	echo "--no-text pkcs12 info failed 2"
 	exit 1
 fi
 
@@ -104,36 +122,4 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
-# test whether we can encode a certificate, a key and a CA
-${VALGRIND} "${CERTTOOL}" --to-p12 --password 123456 --p12-name "my-key" --load-certificate "${srcdir}/../certs/cert-ecc256.pem" --load-privkey "${srcdir}/../certs/ecc256.pem" --load-ca-certificate "${srcdir}/../certs/ca-cert-ecc.pem" --outder --outfile $TMPFILE >/dev/null
-rc=$?
-if test ${rc} != 0; then
-	echo "PKCS12 FATAL encoding 2"
-	exit 1
-fi
-
-${VALGRIND} "${CERTTOOL}" --p12-info --inder --password 123456 --infile $TMPFILE >${TMPFILE_PEM} 2>/dev/null
-rc=$?
-if test ${rc} != 0; then
-	echo "PKCS12 FATAL decrypting/decoding 2"
-	exit 1
-fi
-
-grep "BEGIN ENCRYPTED PRIVATE KEY" ${TMPFILE_PEM} >/dev/null 2>&1
-rc=$?
-
-if test "${rc}" != "0"; then
-	exit ${rc}
-fi
-
-count=`grep -c "BEGIN CERTIFICATE" ${TMPFILE_PEM}`
-
-if test "$count" != "2"; then
-	echo "Only one certificate was included"
-	exit 1
-fi
-
-rm -f ${TMPFILE_PEM} $TMPFILE
-
-#echo "NEON PKCS12 DONE (rc ${ret})"
-exit ${ret}
+exit 0
diff --git a/src/gnutls/tests/cert-tests/pkcs12-corner-cases b/src/gnutls/tests/cert-tests/pkcs12-corner-cases
--- a/src/gnutls/tests/cert-tests/pkcs12-corner-cases
+++ b/src/gnutls/tests/cert-tests/pkcs12-corner-cases
@@ -34,20 +34,35 @@ if test "${GNUTLS_FORCE_FIPS_MODE}" = 1;then
 fi
 
 if ! test -z "${VALGRIND}"; then
-	VALGRIND=$(echo ${VALGRIND}|cut -d ' ' -f 1)
+#	VALGRIND=$(echo ${VALGRIND}|cut -d ' ' -f 1)
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=6"
 fi
 
-DIFF="${DIFF:-diff}"
+. "${srcdir}/../scripts/common.sh"
+
 TMPFILE="pkcs12-corner.$$.tmp"
 
+# Cases from oss-fuzz
+
+cpassword='1234'
+for p12 in "mem-leak.p12";do
+	set -- ${p12}
+	file="$1"
+	${VALGRIND} "${CERTTOOL}" --p12-info --inder --password "${cpassword}" \
+		--infile "${srcdir}/data/${file}" >${TMPFILE} 2>&1
+	rc=$?
+	if test ${rc} != 0 && test ${rc} != 1; then
+		cat ${TMPFILE}
+		echo "PKCS12 FATAL ${file}"
+		exit 1
+	fi
+done
 
 # Check corner cases in PKCS#12 decoding. Typically the structures tested fail
 # in parsing, but we check against crashes, etc. These test cases were taken
 # from Hubert Kario's corpus at: https://github.com/redhat-qe-security/keyfile-corpus
 
 cpassword='Red Hat Enterprise Linux 7.4'
-
 for p12 in "key-corpus-rc2-1.p12" "key-corpus-rc2-2.p12" "key-corpus-rc2-3.p12";do 
 	set -- ${p12}
 	file="$1"
@@ -56,7 +71,27 @@ for p12 in "key-corpus-rc2-1.p12" "key-corpus-rc2-2.p12" "key-corpus-rc2-3.p12";
 	rc=$?
 	if test ${rc} != 0 && test ${rc} != 1; then
 		cat ${TMPFILE}
-		echo "PKCS12 FATAL ${p12}"
+		echo "PKCS12 FATAL ${file}"
+		exit 1
+	fi
+done
+
+for p12 in "key-corpus-rc2-1.p12";do
+	set -- ${p12}
+	file="$1"
+	"${CERTTOOL}" --p12-info --inder --password "${cpassword}" \
+		--infile "${srcdir}/data/${file}" | tr -d '\r' >${TMPFILE} 2>/dev/null
+	rc=$?
+	if test ${rc} != 0 && test ${rc} != 1; then
+		cat ${TMPFILE}
+		echo "Error in output from ${file}"
+		exit 1
+	fi
+
+	check_if_equal ${TMPFILE} "${srcdir}/data/${file}.out"
+	rc=$?
+	if test ${rc} != 0;then
+		echo "Output differs in ${file}.out ${TMPFILE}"
 		exit 1
 	fi
 done
